application: sap-expert-pool
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: apps/images/favicon.ico
  upload: apps/images/favicon.ico
  mime_type: image/x-icon
  
- url: /stylesheets
  static_dir: apps/stylesheets
  
- url: /image
  static_dir: apps/images
  
- url: /.*
  script: main.py

