application: muvmuv
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /admin.*
  script: $PYTHON_LIB/apphosting/ext/admin/__init__.py

- url: /.*
  script: main.py
