login: &login
  adapter: mysql
  host: localhost
  username: root
  password: 
  

development:
  database: typo
  <<: *login

test:
  database: typo_tests
  <<: *login

production:
  database: typo
  <<: *login
