# Pabla - a sample web picture sharing application for AppEngine
# Author: frew@google.com (Fred Wulff)

application: pabla
version: 1
runtime: python
api_version: 1

handlers:
- url: /media
  static_dir: media

- url: /(new|upload.*)
  script: pabla.py
  login: required

- url: /.*
  script: pabla.py
